/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_demo_Demo */

#ifndef _Included_jni_demo_Demo
#define _Included_jni_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_demo_Demo
 * Method:    printMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_demo_Demo_printMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
