/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_example_CriticalRegionExample */

#ifndef _Included_jni_example_CriticalRegionExample
#define _Included_jni_example_CriticalRegionExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_example_CriticalRegionExample
 * Method:    modifyArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_jni_example_CriticalRegionExample_modifyArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
