/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIDemo */

#ifndef _Included_jni_JNIDemo
#define _Included_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIDemo
 * Method:    invokeMethodFromJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIDemo_invokeMethodFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNIDemo
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIDemo_modifyStaticVariable
  (JNIEnv *, jclass);

/*
 * Class:     jni_JNIDemo
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIDemo_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNIDemo
 * Method:    calArraySum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_jni_JNIDemo_calArraySum
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     jni_JNIDemo
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIDemo_printHello
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNIDemo
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_JNIDemo_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
