/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_jep423_JEP423 */

#ifndef _Included_jni_jep423_JEP423
#define _Included_jni_jep423_JEP423
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_jep423_JEP423
 * Method:    modifyArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_jni_jep423_JEP423_modifyArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
